spring:
  datasource:
    url: jdbc:h2:mem:testdb  # H2 ???? DB ??
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true           # H2 ? ?? ???
      path: /h2-console       # H2 ? ?? ?? (?? ??? '/h2-console')
  # ?????? ?? ? ??? ?? ?? (create, update, none, validate ?? ??)
  # none ?? ??
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true            # ???? SQL? ??? ??
